/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Board {
  'description' : string,
  'boardUrl' : string,
  'boardName' : string,
}
export interface Post {
  'title' : string,
  'body' : string,
  'date' : string,
  'slug' : string,
  'imageUrl' : string,
  'excerpt' : string,
}
export interface Product {
  'name' : string,
  'description' : string,
  'affiliateUrl' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : string,
}
export interface _SERVICE {
  'addBoard' : ActorMethod<[string, Board], undefined>,
  'addPost' : ActorMethod<[string, Post], undefined>,
  'addProduct' : ActorMethod<[string, Product], undefined>,
  'getAllBoards' : ActorMethod<[], Array<Board>>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBoardById' : ActorMethod<[string], Board>,
  'getPostById' : ActorMethod<[string], Post>,
  'getProductById' : ActorMethod<[string], Product>,
  'removeBoard' : ActorMethod<[string], undefined>,
  'removePost' : ActorMethod<[string], undefined>,
  'removeProduct' : ActorMethod<[string], undefined>,
  'updateBoard' : ActorMethod<[string, Board], undefined>,
  'updatePost' : ActorMethod<[string, Post], undefined>,
  'updateProduct' : ActorMethod<[string, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];