/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Board = IDL.Record({
  'description' : IDL.Text,
  'boardUrl' : IDL.Text,
  'boardName' : IDL.Text,
});
export const Post = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'date' : IDL.Text,
  'slug' : IDL.Text,
  'imageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
});
export const Product = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'affiliateUrl' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBoard' : IDL.Func([IDL.Text, Board], [], []),
  'addPost' : IDL.Func([IDL.Text, Post], [], []),
  'addProduct' : IDL.Func([IDL.Text, Product], [], []),
  'getAllBoards' : IDL.Func([], [IDL.Vec(Board)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBoardById' : IDL.Func([IDL.Text], [Board], ['query']),
  'getPostById' : IDL.Func([IDL.Text], [Post], ['query']),
  'getProductById' : IDL.Func([IDL.Text], [Product], ['query']),
  'removeBoard' : IDL.Func([IDL.Text], [], []),
  'removePost' : IDL.Func([IDL.Text], [], []),
  'removeProduct' : IDL.Func([IDL.Text], [], []),
  'updateBoard' : IDL.Func([IDL.Text, Board], [], []),
  'updatePost' : IDL.Func([IDL.Text, Post], [], []),
  'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Board = IDL.Record({
    'description' : IDL.Text,
    'boardUrl' : IDL.Text,
    'boardName' : IDL.Text,
  });
  const Post = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'date' : IDL.Text,
    'slug' : IDL.Text,
    'imageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
  });
  const Product = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'affiliateUrl' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Text,
  });
  
  return IDL.Service({
    'addBoard' : IDL.Func([IDL.Text, Board], [], []),
    'addPost' : IDL.Func([IDL.Text, Post], [], []),
    'addProduct' : IDL.Func([IDL.Text, Product], [], []),
    'getAllBoards' : IDL.Func([], [IDL.Vec(Board)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBoardById' : IDL.Func([IDL.Text], [Board], ['query']),
    'getPostById' : IDL.Func([IDL.Text], [Post], ['query']),
    'getProductById' : IDL.Func([IDL.Text], [Product], ['query']),
    'removeBoard' : IDL.Func([IDL.Text], [], []),
    'removePost' : IDL.Func([IDL.Text], [], []),
    'removeProduct' : IDL.Func([IDL.Text], [], []),
    'updateBoard' : IDL.Func([IDL.Text, Board], [], []),
    'updatePost' : IDL.Func([IDL.Text, Post], [], []),
    'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };